included:
    - LikeInstagram

excluded:   # 제외
    - Pods
    - LikeInstagram/Resources/SceneDelegate.swift

force_cast: warning
line_length: 200

type_body_lenth:
    - 1000 # warning
    - 1500 # error
