name: Swift

# trigger when
on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    # 플랫폼 지정
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
